### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:test

**Comment by rigosouza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rigosouza** [comment]
@leoadb LGTM!

**Comment by rigosouza** [comment]
ci:test

**Comment by rigosouza** [comment]
ci:test

**Comment by rigosouza** [comment]
Pull request submitted to https://github.com/rodrigo-e-c-souza/liferay-portal/pull/11. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rigosouza** [comment]
Pull request submitted to https://github.com/rodrigo-e-c-souza/liferay-portal/pull/12. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
